version: '3'
services:
  test:
    build: .
    tty: true
    stdin_open: true
    ports:
      - 8891:8888
    volumes:
      - ./src:/code
      - ./configs:/configs
      - ./scripts:/scripts
      - ./output:/out
      - ./data:/data
      - ./models:/models
    hostname: mlbuild
